query ($id: ID!) {
  getUser(id: $id) {
    _id
    name
    email
    pfp {
      url
      type
      cloudinaryPublicId
    }
    tutor {
      status
    }
    yearGroup
    biography
    academicsLearning
    extrasLearning
    academicsTutoring
    extrasTutoring
    classes {
      _id
      name
      image
    }
    sessions {
      _id
      startTime
    }
  }
}
