#import "./limitedUserInfo.gql"
query ($id: ID!) {
  getUser(id: $id) {
    ...limitedUserInfo
    classes {
      _id
      name
      image
    }
    sessions {
      _id
      startTime
    }
  }
}
