query ($id: ID!) {
  getUser(id: $id) {
    _id
    name
    email
    school
    pfp {
      type
      url
      cloudinaryPublicId
    }
    tutor {
      type
      status
      price
      academicsTutoring
      curricula
      online
      location
    }
    yearGroup
    biography
  }
}
