query($id: ID!) {
  getUser(id: $id) {
    _id
    name
    userType
    email
    pfp
    yearGroup
    biography
    academics
    extras
    classes {
      _id
      name
      image
    }
    sessions {
      _id
      time
    }
  }
}
