fragment limitedUserInfo on User {
  _id
  name
  email
  pfp {
    type
    url
    cloudinaryPublicId
  }
  tutor {
    type
    status
    price
    academicsTutoring
    curricula
  }
  yearGroup
  biography
}
