query Login($email: String, $password: String, $tokenId: String) {
  login(email: $email, password: $password, tokenId: $tokenId) {
    jwt
    exp
    user {
      _id
      name
      userType
      pfp {
        type
        url
        cloudinaryPublicId
      }
      email
      registrationStatus
    }
  }
}
