#import "./authFields.gql"
mutation Register(
  $name: String!
  $email: String!
  $password: String
  $pfp: PfpIn
  $yearGroup: String!
  $school: String!
  $biography: String
  $tertiary: Boolean!
  $token: String!
  $applyTutor: Boolean!
  $tutor: TutorInfoIn
) {
  register(
    name: $name
    email: $email
    password: $password
    pfp: $pfp
    yearGroup: $yearGroup
    school: $school
    biography: $biography
    tertiary: $tertiary
    token: $token
    applyTutor: $applyTutor
    tutor: $tutor
  ) {
    ...authFields
  }
}
