#import "./authFields.gql"
mutation Register(
  $name: String!
  $email: String!
  $password: String
  $pfp: PfpIn
  $yearGroup: String!
  $school: String!
  $academicsTutoring: [String!]
  $biography: String
  $academicRecords: [FileMetaIn!]
  $token: String!
  $applyTutor: Boolean!
) {
  register(
    name: $name
    email: $email
    password: $password
    pfp: $pfp
    yearGroup: $yearGroup
    school: $school
    academicsTutoring: $academicsTutoring
    biography: $biography
    academicRecords: $academicRecords
    token: $token
    applyTutor: $applyTutor
  ) {
    ...authFields
  }
}
