scalar Date
enum UserType {
  TUTEE
  TUTOR
}

input LocationIn {
  address: String
  coords: CoordIn
}

input CoordIn {
  lat: Float
  lng: Float
}

input ClassPreferenceIn {
  publicClass: Boolean
  studentInstantiation: Boolean
  studentAgreeSessions: Boolean
}

input AttendanceIn {
  tutee: ID!
  attended: Boolean
  reason: String
}

input PfpIn {
  type: String!
  url: String!
  cloudinaryPublicId: String
}

input SessionSettingsIn {
  studentEditNotes: Boolean!
  syncTutorsWithClass: Boolean!
  syncTuteesWithClass: Boolean!
}
