mutation UpdatePassword(
  $email: String!
  $passwordResetCode: Int!
  $newPassword: String!
) {
  updatePassword(
    email: $email
    passwordResetCode: $passwordResetCode
    newPassword: $newPassword
  ) {
    jwt
    exp
    user {
      name
      userType
      pfp
      email
      registrationStatus
    }
  }
}
