query getClass($id: ID!, $time: Date!) {
  getClass(id: $id) {
    _id
    name
    sessions(limit: 100, time: $time) {
      _id
      startTime
      tutees {
        _id
        name
      }
      attendance {
        tutee
        attended
        reason
      }
    }
  }
}
