query GetChat($channel: ID!, $skip: Int, $limit: Int) {
  getChat(channel: $channel, skip: $skip, limit: $limit) {
    bindToClass
    users {
      _id
      name
    }
    class {
      name
    }
    messages {
      _id
      type
      time
      sessionId
      sessionTime
      author
      text
    }
  }
}
