query GetChat($channel: ID!) {
  getChat(channel: $channel) {
    bindToClass
    users {
      _id
      name
    }
    class {
      name
    }
    messages {
      _id
      type
      time
      sessionId
      sessionTime
      author
      text
    }
  }
}
