query GetPendingTutors {
  getPendingTutors {
    _id
    name
    email
    pfp {
      url
    }
    tutor {
      type
      status
      academicRecords {
        id
        name
        size
        type
        link
      }
      academicsTutoring
      curricula
      price
      online
      location
    }
    biography
    yearGroup
    school
  }
}
