query GetChats($userID: ID!) {
  getChatsOfUser(userID: $userID) {
    channel
    bindToClass
    class {
      name
    }
    users {
      _id
      name
    }
    messages(limit: 1) {
      type
      time
      author
      text
    }
  }
}
