query GetUser {
  getUser {
    _id
    name
    userType
    email
    pfp {
      type
      url
      cloudinaryPublicId
    }
    yearGroup
    biography
    academics
    extras
    school
  }
}
