mutation updateUser(
  $id: ID!
  $name: String
  $pfp: PfpIn
  $yearGroup: Int
  $biography: String
  $school: String
  $academicsLearning: [String!]
  $extrasLearning: [String!]
  $academicsTutoring: [String!]
  $extrasTutoring: [String!]
) {
  updateUser(
    id: $id
    name: $name
    pfp: $pfp
    yearGroup: $yearGroup
    biography: $biography
    academicsLearning: $academicsLearning
    extrasLearning: $extrasLearning
    academicsTutoring: $academicsTutoring
    extrasTutoring: $extrasTutoring
    school: $school
  ) {
    _id
    name
    email
    pfp {
      type
      url
      cloudinaryPublicId
    }
    yearGroup
    biography
    academicsLearning
    extrasLearning
    academicsTutoring
    extrasTutoring
    school
  }
}
