#import "./userInfo.gql"
mutation updateUser(
  $id: ID!
  $name: String
  $pfp: PfpIn
  $yearGroup: String
  $biography: String
  $school: String
  $tertiary: Boolean
  $applyTutor: Boolean
  $tutor: TutorInfoIn
) {
  updateUser(
    id: $id
    name: $name
    pfp: $pfp
    yearGroup: $yearGroup
    biography: $biography
    school: $school
    tertiary: $tertiary
    applyTutor: $applyTutor
    tutor: $tutor
  ) {
    ...userInfo
  }
}
