fragment userInfo on User {
  _id
  name
  email
  pfp {
    type
    url
    cloudinaryPublicId
  }
  tutor {
    type
    status
    academicRecords {
      id
      name
      size
      type
      link
    }
    academicsTutoring
    curricula
    price
    location
    online
  }
  yearGroup
  biography
  school
}
