query GetClass($id: ID!, $sessionLimit: Int, $oldSessions: Boolean!) {
  getClass(id: $id) {
    _id
    name
    sessions(limit: $sessionLimit, old: $oldSessions) {
      _id
      startTime
    }
    tutees {
      _id
      name
    }
    tutors {
      _id
      name
      pfp {
        url
        type
        cloudinaryPublicId
      }
    }
    description
    location {
      address
      coords {
        lat
        lng
      }
    }
    videoLink
    pricePerTutee
    tags
    date
    image
    preferences {
      online
      publicClass
      studentInstantiation
      studentAgreeSessions
      enableChat
    }
    chat {
      channel
    }
  }
}
