query GetClass($id: ID!, $sessionLimit: Int) {
  getClass(id: $id) {
    _id
    name
    sessions(limit: $sessionLimit) {
      _id
      startTime
    }
    tutees {
      _id
      name
    }
    tutors {
      _id
      name
      pfp
    }
    description
    location {
      address
      coords {
        lat
        lng
      }
    }
    pricePerTutee
    tags
    date
    image
    preferences {
      publicClass
      studentInstantiation
      studentAgreeSessions
    }
  }
}
