mutation UpdateClass(
  $id: ID!
  $name: String
  $location: LocationIn
  $description: String
  $date: String
  $tags: [String!]
  $tutors: [ID!]
  $tutees: [ID!]
  $preferences: ClassPreferenceIn
) {
  updateClass(
    id: $id
    name: $name
    description: $description
    date: $date
    tags: $tags
    tutors: $tutors
    tutees: $tutees
    location: $location
    preferences: $preferences
  ) {
    _id
    name
    description
    date
    tags
    location {
      address
      coords {
        lat
        lng
      }
    }
    tutors {
      _id
      name
      pfp {
        url
        type
        cloudinaryPublicId
      }
    }
    tutees {
      _id
      name
    }
    preferences {
      online
      publicClass
      studentInstantiation
      studentAgreeSessions
      enableChat
    }
    videoLink
    chat {
      channel
    }
  }
}
