mutation UpdateClass(
  $id: ID!
  $name: String
  $location: LocationIn
  $description: String
  $tutors: [ID!]
  $preferences: ClassPreferenceIn
) {
  updateClass(
    id: $id
    name: $name
    description: $description
    tutors: $tutors
    location: $location
    preferences: $preferences
  ) {
    _id
    name
    description
    location {
      address
      coords {
        lat
        lng
      }
    }
    tutors {
      _id
      name
      pfp
    }
  }
}
