query GetInfo($userID: ID!) {
  getSessionsOfUser(userID: $userID, limit: 2) {
    _id
    startTime
    location {
      address
    }
  }
  getClassesOfUser(userID: $userID, limit: 1) {
    _id
    name
    image
    description
  }
  getTutorsOfUser(userID: $userID, limit: 4) {
    _id
    name
    pfp {
      url
      type
      cloudinaryPublicId
    }
  }
}
